---
blank_issues_enabled: false
contact_links:
  - name: FlutterMasteryLibrary.com Community Support
    url: https://github.com/MasteryEducation/FlutterMasteryLibrary.com/discussions
    about: Please ask and answer questions here.
